name: Firebase Deploy

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Ensure the Node.js version matches your project requirements

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Google Cloud SDK
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list > /dev/null
        sudo apt-get install apt-transport-https ca-certificates gnupg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install google-cloud-sdk

    - name: Set up Firebase Authentication
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT_KEY > "${HOME}/firebase-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/firebase-key.json"

    - name: Deploy to Firebase
      run: firebase deploy --project websampleone-f087b --token "$(gcloud auth print-access-token)"
