name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js version 18.x

    - name: Install Firebase Tools
      run: npm install -g firebase-tools  # Install Firebase CLI via npm

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Set up Google Application Credentials
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/service-account.json
        echo "Service account key created"

    - name: Deploy to Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json  # Set the environment variable for the service account key
      run: firebase deploy --project websampleone-f087b  # Deploy to your Firebase project
