name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js version 18.x

    - name: Install Firebase Tools
      run: npm install -g firebase-tools  # Install Firebase CLI

    - name: Deploy to Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  # Use the service account
      run: firebase deploy --project websampleone-f087b
