name: Firebase Deploy

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Ensure to use a Node.js version that works with Firebase

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT_KEY > ${HOME}/firebase-key.json
        firebase auth:import ${HOME}/firebase-key.json --project websampleone-f087b

    - name: Deploy to Firebase
      run: firebase deploy --project websampleone-f087b --non-interactive
